# Generated by Django 3.0.7 on 2020-07-02 18:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    verbose_name='id'
                )),
                ('name', models.CharField(
                    max_length=100,
                    verbose_name='name'
                )),
                ('created_at',
                 models.DateTimeField(
                     default=django.utils.timezone.now,
                     editable=False,
                     verbose_name='created_at'
                 )),
            ],
        ),
    ]
