# Generated by Django 3.0.7 on 2020-06-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=100, verbose_name='authorName')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('text', models.TextField(verbose_name='text')),
                ('authorId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restapi.Account')),
            ],
        ),
    ]
